general{
  lock_cmd = pidof hyprlock || hyprlock #ensures hyprlock runs only once
}	

listener {
  timeout = 600			#10 min 
  on-timeout = loginctl lock-session		#locks after 5min
}

listener {
  timeout = 1800
  on-timeout = systemctl suspend
}
