# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace

$font = JetBrains Mono Extrabold


$seafoam= rgba(165,190,189,1)
$midnight_green = rgba(15, 74, 81, 1)

$orange_bak = rgba(254, 128, 25, 1)
$orange = rgba(55,7,2,1)
$red_bak = rgba(248, 85, 82, 1)
$red = rgba(81,15,41,1) 



$dominant_color = $seafoam
$accent_color = $midnight_green

general {
    hide_cursor = true
    fail_timeout = 900
}

background {
    monitor =
    path = ~/.config/hypr/waterfall.jpg
    blur_passes = 2
}


animations {
    enabled = false
}

## input field aesthetics
input-field {
    monitor =

    ## general / neutral state
    size = 300, 60
    inner_color = $dominant_color

    outline_thickness = 3
    outer_color = $accent_color
    rounding = -1 

    font_color = $accent_color
    font_family = $font
    placeholder_text = 

    check_color = $accent_color
    fail_color = $red
    fail_text = 

    fade_on_empty = false #need to decide if i want this
    fade_timeout = 300 #milliseconds before fade_on_empty triggered


    ## dots 
    dots_size = 0.20 						#TBD
    dots_spacing = 0.20
    dots_center = false	#aligns left				#TBD

    ## caps lock & number lock
    capslock_color = rgb(69,133,136)
    ##numlock_color = rgb(177,98,134)
    ##invert_numlock = true
	
    position = 0, -20
    halign = center
    valign = center   
}

# TIME
label {
  monitor = 

  text = cmd[update:1000] date +"%-I:%M%P" | tr 'a-z' 'A-Z' # tr - makes upper case
  color = $dominant_color
  font_size = 120
  font_family = $font

  position = 0, 25%
  halign = center
  valign = center
}

# DATE
label {
    monitor =

    text = cmd[update:60000] date +"%A, %d %B" # update every 60 seconds
    color = $dominant_color
    font_size = 30
    font_family = $font

    position = 0, 15.5%
    halign = center
    valign = center
}


# power menu - not using currently
label {
    monitor =
    text =   
    color = $light_grey
    font_size = 50
    font_family = $font #not sure if this does anything

    onclick = systemctl poweroff

    position = 0, 50
    halign = center
    valign = bottom

}
